apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aletheia-prod

resources:
- ../../base/
- ingress.yaml
- hpa.yaml
- network-policy.yaml
- pod-disruption-budget.yaml

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: aletheia-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=WARNING
  - DEBUG=false

secretGenerator:
- name: aletheia-secrets
  env: .env.production

images:
- name: ghcr.io/saptiva-ai/alethia_deepresearch
  newTag: latest

replicas:
- name: aletheia
  count: 3

commonLabels:
  environment: production
  version: stable

commonAnnotations:
  aletheia.ai/environment: production