apiVersion: apps/v1
kind: Deployment
metadata:
  name: aletheia
spec:
  template:
    spec:
      containers:
      - name: aletheia
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"