apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aletheia-staging

resources:
- ../../base/
- ingress.yaml

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: aletheia-config
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=INFO
  - DEBUG=false

secretGenerator:
- name: aletheia-secrets
  env: .env.staging

images:
- name: ghcr.io/saptiva-ai/alethia_deepresearch
  newTag: develop

replicas:
- name: aletheia
  count: 2

commonLabels:
  environment: staging
  version: develop

commonAnnotations:
  aletheia.ai/environment: staging