name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      clear_cache:
        description: 'Clear pip cache'
        required: false
        default: 'false'
        type: boolean

env:
  PYTHON_VERSION: "3.11"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: ${{ inputs.clear_cache == 'true' && '' || 'pip' }}
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]

      - name: Verify installation
        run: |
          python -c "import domain.models.evidence; print('✅ Domain models import successful')"
          python -c "import pytest; print(f'✅ Pytest version: {pytest.__version__}')"
          python -m pytest --version
          echo "🔍 Checking individual test files..."
          for test_file in tests/unit/test_*.py; do
            echo "Testing import: $test_file"
            python -c "import sys; sys.path.insert(0, '.'); exec(open('$test_file').read())" 2>&1 || echo "❌ Failed to import $test_file"
          done
          echo "🔍 Running test collection with verbose errors..."
          python -m pytest --collect-only tests/unit/ -v || echo "❌ Test collection failed"

      - name: Run Ruff
        run: ruff check . --output-format=github

      - name: Run Black
        run: black --check --diff .

      - name: Run MyPy (domain models)
        run: mypy domain/models --ignore-missing-imports

      - name: Run unit tests with coverage
        env:
          SAPTIVA_API_KEY: "mock_key_for_testing"
          TAVILY_API_KEY: "mock_key_for_testing"
          VECTOR_BACKEND: "none"
          ENVIRONMENT: "test"
        run: |
          python -m pytest tests/unit/ \
            --html=test-results.html \
            --json-report --json-report-file=test-results.json \
            -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.html
            test-results.json
            coverage.xml
            htmlcov/
