name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  PYTHON_VERSION: "3.11"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]

      - name: Run Ruff
        run: ruff check . --output-format=github

      - name: Run Black
        run: black --check --diff .

      - name: Run MyPy (domain models)
        run: mypy domain/models --ignore-missing-imports

      - name: Run unit tests with coverage
        env:
          SAPTIVA_API_KEY: "mock_key_for_testing"
          TAVILY_API_KEY: "mock_key_for_testing"
          VECTOR_BACKEND: "none"
          ENVIRONMENT: "test"
        run: |
          python -m pytest tests/unit/ \
            --cov=domain --cov=adapters --cov=apps \
            --cov-report=xml --cov-report=html --cov-report=term-missing \
            --html=test-results.html \
            --json-report --json-report-file=test-results.json \
            --tb=short -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.html
            test-results.json
            coverage.xml
            htmlcov/
